# Devices that should only be paired on hci0 (music adapter).
# One MAC per line. If found paired on hci1 (voice), pairing is removed.
D4:3A:2C:64:87:9E  # Pixel 8 Pro
D4:3A:2C:99:52:BE  # Pixel 7 Pro
6C:2F:8A:E6:ED:10  # Tab A7 Lite
