namespace Radio.Core.Models;

/// <summary>
/// A 3-day forecast for a single location. The API returns this DTO as the
/// payload of <c>GET /api/weather/forecast</c>; the kiosk sleep screen renders
/// it alongside the LED wall clock on alternate drift cycles.
/// </summary>
/// <param name="Zip">ZIP code the forecast was retrieved for.</param>
/// <param name="LocationName">
/// Human-readable place name (e.g. <c>"Pittsboro, NC"</c>). Sourced from the
/// ZIP-to-coordinates lookup; falls back to the raw ZIP if the geocoder doesn't
/// return a place name.
/// </param>
/// <param name="GeneratedAtUtc">
/// Wall-clock time the upstream forecast was generated by NWS
/// (<c>forecastGenerator.generatedAt</c>). Used by the UI to show "as of HH:mm"
/// and by callers to detect stale data.
/// </param>
/// <param name="FetchedAtUtc">
/// Wall-clock time WE fetched/refreshed this forecast. Diverges from
/// <see cref="GeneratedAtUtc"/> when we serve cached data.
/// </param>
/// <param name="IsStale">
/// <c>true</c> when the cache entry is past its TTL but is being served because
/// the upstream fetch failed (stale-while-revalidate). UI should render a
/// subtle "stale" affordance in this case.
/// </param>
/// <param name="Days">
/// Up to three entries: today, tomorrow, day-after. The service guarantees
/// chronological order. May contain fewer than three entries when NWS returned
/// fewer forecast periods (e.g. late-evening boundary case); the UI centers
/// the cards it has rather than rendering placeholders.
/// </param>
public sealed record WeatherForecast(
  string Zip,
  string LocationName,
  DateTimeOffset GeneratedAtUtc,
  DateTimeOffset FetchedAtUtc,
  bool IsStale,
  IReadOnlyList<WeatherDay> Days);
